bind = $mainMod, s, exec, hyprshot -m region --clipboard-only
bind = $mainMod SHIFT, s, exec, hyprshot -m window -m active --clipboard-only
bind = $mainMod CTRL, s, exec, hyprshot -m output --clipboard-only
