exec-once = waybar 2>&1 > ~/somelog.txt
exec-once = wezterm
exec-once = blueman-applet
exec-once = hyprpaper
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
