# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0ce0df7d-4bf6-4a56-911a-8ca6a567f8fd";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-e3761d89-2e71-476d-b4bf-e9c64e0507f3".device =
    "/dev/disk/by-uuid/e3761d89-2e71-476d-b4bf-e9c64e0507f3";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A450-7E1F";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/1c24430e-f729-4942-afad-fa5388f8047d"; }
  ];

  hardware.enableRedistributableFirmware = true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
