$monitorLeft = DP-2 # desc:Dell Inc. DELL P2423D 31CSVP3
$monitorCenter = DP-3 # desc:Dell Inc. DELL P2723DE GQ320N3
$monitorRight = DP-4 # desc:Dell Inc. DELL P2423D 5QRC1L3

monitor=$monitorLeft,2560x1440,0x0,1,bitdepth,8
monitor=$monitorCenter,2560x1440,2560x0,1,bitdepth,8
monitor=$monitorRight,2560x1440,5120x0,1,bitdepth,8

workspace=1, monitor:$monitorCenter
workspace=2, monitor:$monitorCenter
workspace=3, monitor:$monitorCenter
workspace=4, monitor:$monitorCenter
workspace=5, monitor:$monitorCenter

workspace=6, monitor:$monitorLeft
workspace=7, monitor:$monitorLeft

workspace=8, monitor:$monitorRight
workspace=9, monitor:$monitorRight

# exec-once = [workspace 1 silent] ${terminal}
exec-once = [workspace 6 silent] ${terminal}
# exec-once = [workspace 8 silent] ${terminal}

# windowrulev2 = workspace 6,class:Slack
# windowrulev2 = workspace 8,class:jetbrains-datagrip

workspace = s[true], gapsout:30
