# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e922f54d-df3f-49ef-b410-1404fefb70e3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6840cd5e-49c5-4c8e-814e-8d212ff8114d".device = "/dev/disk/by-uuid/6840cd5e-49c5-4c8e-814e-8d212ff8114d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CDAC-1E6E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c8241676-3dbe-44b8-8049-15d1d4179c33"; }
    ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
