monitor=eDP-1,1920x1200,0x0,1.5,bitdepth,8
monitor=DP-2,5120x1440,1920x0,1,bitdepth,8
monitor=DP-3,5120x1440,1920x0,1,bitdepth,8

bindl=,switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
bindl=,switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 1920x1200, 0x0, 1.5"

general {
    layout = dwindle
  }
