# BACKGROUND
background {
    color = rgb(0, 0, 0)
}

auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250 # in milliseconds
    }
}

# GENERAL
general {
    no_fade_in = true
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M") // $USER</span>"
    color = rgba(216, 222, 233, .7)
    font_size = 12
    position = 0, 50
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 40
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    inner_color = rgba(255, 255, 255)
    font_color = rgb(0, 0, 0)
    fade_on_empty = false
    placeholder_text = 
    hide_input = false
    position = 0, 0
    rounding = 0
    halign = center
    valign = center
}
