format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$nodejs\
$time\
$cmd_duration\
$line_break\
$character"""

palette = "moonfly"

[nodejs]
format = '$symbol$version'

[c]
style = "green"

[directory]
style = "fern"

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[V ❮](lavender)"

[git_branch]
format = "[$branch]($style)"
style = "lavender"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "fern"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "lavender"

[cmd_duration]
format = "[$duration]($style) "
style = "orange"

[package]
style = "orange"

[terraform]
style = "purple"

[palettes.moonfly]
fern = "#87d787"
lavender = "#adadf3"
orange = "#f09479"
red = "#f07496"

