[main]
font=JetBrains Mono:size=9
gamma-correct-blending=true

[colors]
cursor = 080808 9e9e9e
foreground = bdbdbd
background = 080808

# selection-foreground = 080808
# selection-background = b2ceee

regular0 = 323437
regular1 = FF5454
regular2 = 8CC85F
regular3 = E3C78A
regular4 = 80A0FF
regular5 = CF87E8
regular6 = 79DAC8
regular7 = C6C6C6

bright0 = 949494
bright1 = FF5189
bright2 = 36C692
bright3 = C2C292
bright4 = 74B2FF
bright5 = AE81FF
bright6 = 85DC85
bright7 = E4E4E4
